version: '3.9'

services:
    nginx:
        image: nginx:latest
        container_name: nginx_gateway
        ports:
            - '80:80'
        volumes:
            - ./gateway/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - frontend
            - auth-service
            - product-service
            - order-service
            - payment-service
            - cart-service
            - notification-service
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend/ecommerce
            dockerfile: Dockerfile
        container_name: frontend
        volumes:
            - ./frontend/ecommerce:/app
            - /app/node_modules
        ports:
            - '3000:5173'
        networks:
            - app-network

    auth-service:
        build:
            context: ./backend/auth-service
            dockerfile: ../../docker/node.Dockerfile
        container_name: auth-service
        volumes:
            - ./backend/auth-service:/app
            - /app/node_modules
        ports:
            - '5001:5000'
        env_file:
            - .env
        depends_on:
            - mongo
            - redis
            - rabbitmq
        networks:
            - app-network

    product-service:
        build:
            context: ./backend/product-service
            dockerfile: ../../docker/node.Dockerfile
        container_name: product-service
        volumes:
            - ./backend/product-service:/app
            - /app/node_modules
        ports:
            - '5002:5000'
        env_file:
            - .env
        networks:
            - app-network

    order-service:
        build:
            context: ./backend/order-service
            dockerfile: ../../docker/node.Dockerfile
        container_name: order-service
        volumes:
            - ./backend/order-service:/app
            - /app/node_modules
        ports:
            - '5003:5000'
        env_file:
            - .env
        depends_on:
            - mongo
            - redis
            - rabbitmq
        networks:
            - app-network

    payment-service:
        build:
            context: ./backend/payment-service
            dockerfile: ../../docker/node.Dockerfile
        container_name: payment-service
        volumes:
            - ./backend/payment-service:/app
            - /app/node_modules
        ports:
            - '5004:5000'
        env_file:
            - .env
        depends_on:
            - mongo
            - redis
            - rabbitmq
        networks:
            - app-network

    cart-service:
        build:
            context: ./backend/cart-service
            dockerfile: ../../docker/node.Dockerfile
        container_name: cart-service
        volumes:
            - ./backend/cart-service:/app
            - /app/node_modules
        ports:
            - '5005:5000'
        env_file:
            - .env
        networks:
            - app-network

    notification-service:
        build:
            context: ./backend/notification-service
            dockerfile: ../../docker/node.Dockerfile
        container_name: notification-service
        volumes:
            - ./backend/notification-service:/app
            - /app/node_modules
        ports:
            - '5006:5000'
        env_file:
            - .env
        depends_on:
            - rabbitmq
        networks:
            - app-network
    inventory-service:
        build:
            context: ./backend/inventory-service
            dockerfile: ../../docker/node.Dockerfile
        container_name: inventory-service
        volumes:
            - ./backend/inventory-service:/app
            - /app/node_modules
        ports:
            - '5007:5000'
        env_file:
            - .env
        depends_on:
            - rabbitmq
        networks:
            - app-network

    mongo:
        image: mongo:7
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db
        networks:
            - app-network

    redis:
        image: redis:7
        container_name: redis
        ports:
            - '6379:6379'
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - app-network

networks:
    app-network:

volumes:
    mongo-data:
