events {}

http {
  upstream auth_service {
    server auth-service:5000;
  }

  upstream product_service {
    server product-service:5000;
  }

  upstream order_service {
    server order-service:5000;
  }

  upstream payment_service {
    server payment-service:5000;
  }

  upstream cart_service {
    server cart-service:5000;
  }

  upstream notification_service {
    server notification-service:5000;
  }

  server {
    listen 80;

    location /api/auth/ {
      proxy_pass http://auth_service;
    }

    location /api/products/ {
      proxy_pass http://product_service;
    }

    location /api/orders/ {
      proxy_pass http://order_service;
    }

    location /api/payments/ {
      proxy_pass http://payment_service;
    }

    location /api/cart/ {
      proxy_pass http://cart_service;
    }

    location /api/notifications/ {
      proxy_pass http://notification_service;
    }
  }
}